### PR TITLE
Update: add new API to list funding, geographical area and get detail…

### PR DESCRIPTION
**Pull request by macloux**
… of project

### CODE REVIEW

**Comment by macloux** [comment]
@cpina, Do you have time to merge it? We need those changes to continue development.

**Comment by cpina** [comment]
I'll do it now. Please note that tomorrow and next week I'm off.

**Review by cpina — APPROVED** [review]

**Comment by cpina** [comment]
Done and deployed on staging.

I've also updated the staging branch (there were conflicts due to other changes in the file projects.py)

Have a good holiday period!

**Comment by macloux** [comment]
Thanks you too have nice holidays.

**Pull request merged**
