### PR TITLE
Remove basic auth for accessing staging API

### PR DESCRIPTION
**Pull request by macloux**
Due to restriction with REST API we can't manage 2 authentications in same request. So I propose to remove basic auth to access /api/v1/ path.

### CODE REVIEW

**Comment by cpina** [comment]
> Due to restriction with REST API we can't manage 2 authentications in same request

At the moment I only see one authentication (the one removed). Are you adding a second one for the API so only our authenticated client can make requests?

Before disabling the nginx authentication I think that it might be good to make some improvements on the API to avoid exposing data that is not meant to be public:

- Filter out Projects with status=Project.ABORTED  (or just include the ONGOING and COMPLETED)
- I think that it would be good to expose only the latest LaySummary of type `Web` (I cannot remember the type exactly now). Other LaySummaries are drafts and originals and might be better to not be exposed on the API.
- (optional) For the Medium it might be that only Medium with a license can be exposed but this is a question from Pauline (I will answer it later today or Monday morning).
- 

And about this PR: I haven't tested it (and I'm happy to merge it after the changes) but I thought that the block `location /api/v1/` needs to be above `location /` or nginx will match `/` and request the password. But after addressing the filtering I can merge and test quickly :-)

**Comment by macloux** [comment]
> > Due to restriction with REST API we can't manage 2 authentications in same request
> 
> At the moment I only see one authentication (the one removed). Are you adding a second one for the API so only our authenticated client can make requests?
> 
> Before disabling the nginx authentication I think that it might be good to make some improvements on the API to avoid exposing data that is not meant to be public:
> 
>     * Filter out Projects with status=Project.ABORTED  (or just include the ONGOING and COMPLETED)
> 
>     * I think that it would be good to expose only the latest LaySummary of type `Web` (I cannot remember the type exactly now). Other LaySummaries are drafts and originals and might be better to not be exposed on the API.
> 
>     * (optional) For the Medium it might be that only Medium with a license can be exposed but this is a question from Pauline (I will answer it later today or Monday morning).
> 
> 
> About this PR: I haven't tested it (and I'm happy to merge it after the changes) but I thought that the block `location /api/v1/` needs to be above `location /` or nginx will match `/` and request the password. But after addressing the filtering I can merge and test quickly :-)

For the API exposing, I can update the code in an other PR.

And no need to move the location, nginx will match the longest first (http://nginx.org/en/docs/http/ngx_http_core_module.html#location)

**Comment by cpina** [comment]
> And no need to move the location, nginx will match the longest first (http://nginx.org/en/docs/http/ngx_http_core_module.html#location)

Thanks! I didn't know it!

> For the API exposing, I can update the code in an other PR.

Good! I'll merge and deploy both at the same time. Thanks!

**Comment by cpina** [comment]
Deployed on staging. Thanks!

**Pull request merged**
